<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Theme Learnbook - version file
 *
 * @package    theme_learnbook
 * @copyright  2020 eCreators PTY LTD
 * @author     2020 Lupiya Mujala, eCreators <lupiya.mujala@ecreators.com.au>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace theme_learnbook\output\core;

defined('MOODLE_INTERNAL') || die;

require_once($CFG->dirroot.'/course/renderer.php');

use moodle_url;

class course_renderer extends \core_course_renderer {

    public function frontpage()
    {
        global $CFG;
        $learnbook_config = get_config('theme_learnbook');
        if(!isloggedin() && $learnbook_config->use_alternate_home_page){
            $home = new moodle_url($CFG->wwwroot . '/local/ecommerce/store.php');
            redirect($home);
        }else {
            return parent::frontpage(); // TODO: Change the autogenerated stub
        }
    }
}
