<?php
namespace theme_learnbook\output\core;

defined('MOODLE_INTERNAL') || die;

require_once($CFG->dirroot.'/course/renderer.php');

use cm_info;
use core\event\user_loggedin;
use core_availability\info;
use pix_icon;

use core_text;
use html_writer;
use context_course;
use moodle_url;
use coursecat_helper;
use lang_string;
use course_in_list;
use stdClass;
use renderable;
use action_link;


class course_renderer extends \core_course_renderer {

    public function frontpage()
    {
        global $CFG;
        $learnbook_config = get_config('theme_learnbook');
        if(!isloggedin() && $learnbook_config->use_alternate_home_page){
            $home = new moodle_url($CFG->wwwroot . '/local/ecommerce/store.php');
            redirect($home);
        }else {
            return parent::frontpage(); // TODO: Change the autogenerated stub
        }
    }
}